[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore dev and test environment JWT keys - They are for the local dev and test environment only.
    '''keys\/INSECURE-dev-jwt-private-key.pem$''',
  ]
