apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tarsy-backend
  namespace: tarsy
spec: {}

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tarsy-dashboard
  namespace: tarsy
spec: {}
