apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistentvolumeclaims.yaml
  - database-deployment.yaml
  - backend-deployment.yaml
  - dashboard-deployment.yaml
  - services.yaml
  - routes.yaml
  - imagestreams.yaml

commonLabels:
  app: tarsy

images:
  - name: tarsy-backend
    newTag: latest
  - name: tarsy-dashboard
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: "17"
  - name: oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    newTag: latest
