apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - persistentvolumeclaims.yaml
  - database-deployment.yaml
  - backend-deployment.yaml
  - dashboard-deployment.yaml
  - services.yaml
  - routes.yaml
  - imagestreams.yaml

commonLabels:
  app: tarsy

configMapGenerator:
  - name: agents-config
    behavior: create
    files:
      - agents.yaml=config/agents.yaml
  - name: llm-providers-config
    behavior: create
    files:
      - llm_providers.yaml=config/llm_providers.yaml
  - name: oauth2-config
    behavior: create
    files:
      - oauth2-proxy.cfg=config/oauth2-proxy-container.cfg

images:
  - name: tarsy-backend
    newTag: latest
  - name: tarsy-dashboard
    newTag: latest
  - name: postgres
    newName: postgres
    newTag: "17"
  - name: oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    newTag: latest
