apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tarsy-secrets
  annotations:
    description: "TARSy secrets template - creates secrets from environment variables"
    tags: "tarsy,secrets"
parameters:
  - name: NAMESPACE
    description: "Target namespace for secrets"
    value: "tarsy-dev"
  - name: GOOGLE_API_KEY
    description: "Google API key for LLM access"
    required: true
  - name: GITHUB_TOKEN
    description: "GitHub token for runbook repository access"
    required: true
  - name: OPENAI_API_KEY
    description: "OpenAI API key (optional)"
    value: ""
  - name: ANTHROPIC_API_KEY
    description: "Anthropic API key (optional)"
    value: ""
  - name: XAI_API_KEY
    description: "X.AI API key (optional)" 
    value: ""
  - name: DATABASE_PASSWORD
    description: "Database password"
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: DATABASE_USER
    description: "Database username"
    value: "tarsy"
  - name: DATABASE_NAME
    description: "Database name"
    value: "tarsy"
  - name: DATABASE_HOST
    description: "Database host"
    value: "dev-tarsy-database"
  - name: DATABASE_PORT
    description: "Database port"
    value: "5432"
  - name: OAUTH2_CLIENT_ID
    description: "OAuth2 client ID (optional for dev)"
    value: ""
  - name: OAUTH2_CLIENT_SECRET
    description: "OAuth2 client secret (optional for dev)"
    value: ""
  - name: OAUTH2_COOKIE_SECRET
    description: "OAuth2 cookie secret"
    generate: expression
    from: "[a-zA-Z0-9]{32}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: tarsy-secrets
      namespace: ${NAMESPACE}
      labels:
        app: tarsy
        component: secrets
    type: Opaque
    stringData:
      google-api-key: ${GOOGLE_API_KEY}
      github-token: ${GITHUB_TOKEN}
      openai-api-key: ${OPENAI_API_KEY}
      anthropic-api-key: ${ANTHROPIC_API_KEY}
      xai-api-key: ${XAI_API_KEY}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: database-secret
      namespace: ${NAMESPACE}
      labels:
        app: tarsy
        component: database
    type: Opaque
    stringData:
      # Used by PostgreSQL database deployment to initialize the database
      password: ${DATABASE_PASSWORD}
      username: tarsy
      database: tarsy
      # Used by TARSy backend deployment for database connection
      database-url: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: oauth2-proxy-secret
      namespace: ${NAMESPACE}
      labels:
        app: tarsy
        component: oauth2-proxy
    type: Opaque
    stringData:
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
      cookie-secret: ${OAUTH2_COOKIE_SECRET}
