"""add mcp_selection to alert_sessions

Revision ID: da4300b74d0e
Revises: 9f8e7d6c5b4a
Create Date: 2025-11-03 22:57:17.531702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4300b74d0e'
down_revision: Union[str, Sequence[str], None] = '9f8e7d6c5b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcp_selection', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_sessions', schema=None) as batch_op:
        batch_op.drop_column('mcp_selection')

    # ### end Alembic commands ###
