"""Initial schema baseline

Revision ID: ae85467a75d2
Revises:
Create Date: 2025-10-02 20:33:15.353864

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ae85467a75d2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
