apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tarsy-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

configMapGenerator:
  - name: agents-config
    behavior: create
    files:
      - agents.yaml
  - name: llm-providers-config
    behavior: create
    files:
      - llm_providers.yaml
  - name: oauth2-config
    behavior: create
    files:
      - oauth2-proxy.cfg=oauth2-proxy-container.cfg
  - name: oauth2-templates
    behavior: create
    files:
      - sign_in.html=templates/sign_in.html
      - tarsy-logo.png=templates/tarsy-logo.png
  - name: tarsy-config
    behavior: create
    literals:
      - LLM_PROVIDER=google-default
      - HISTORY_ENABLED=true
      - HISTORY_RETENTION_DAYS=90
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000
      - AGENT_CONFIG_PATH=/app/config/agents.yaml
      - LLM_CONFIG_PATH=/app/config/llm_providers.yaml

images:
  - name: tarsy-backend
    newName: image-registry.openshift-image-registry.svc:5000/tarsy-dev/tarsy-backend
    newTag: dev
  - name: tarsy-dashboard
    newName: image-registry.openshift-image-registry.svc:5000/tarsy-dev/tarsy-dashboard
    newTag: dev